### ISSUE TITLE
TypeError: Cannot read property 'authorId' of undefined

### ISSUE THREAD

**Issue by moonrailgun** [ether/ep_user_displayname#7]
I  am try to use openid and displayName not work, then i found the new version should install [ep_user_displayname](https://github.com/ether/ep_user_displayname#readme)

so i add this plugin into my plugin list and then throw those error.

![image](https://user-images.githubusercontent.com/6964737/161010975-9ff34942-2ca2-4218-ab3c-8d4fb8f2ebf3.png)

Here is my config: 
```
"ep_user_displayname": {
    "changeableByDefault": false
  },
  "ep_openid_connect": {
    "issuer": "${OPENID_CONNECT_ISSUER}",
    "client_id": "${OPENID_CONNECT_ID}",
    "client_secret": "${OPENID_CONNECT_SECRET}",
    "base_url": "${OPENID_CONNECT_BASEURL}",
    "scope": ["openid", "profile"],
    "user_properties": {
      "displayname": {
        "claim": "nickname"
      }
    }
  },
```

and the version of `etherpad` is sync to master branch.

For more information, here is my fork: https://github.com/msgbyte/etherpad-lite

**Comment by moonrailgun** [comment]
well, when i switch my code to 1.9 in `develop` branch, everything is ok. 

can i trust develop branch?

**Comment by rhansen** [comment]
Thanks for reporting, it should be fixed now.

> can i trust develop branch?

Generally yes. New bugs land on `develop` first, so there's a chance that you'll hit an Etherpad bug that isn't on `master`. But I usually notice those fairly quickly and get them fixed right away. However: I usually test plugins against `develop`, so there's a chance that a plugin change will introduce a compatibility problem that only affects `master` (like this one).
